#!/bin/bash

# File paths
JOURNAL_FILE="journal.txt"

# Check if journal.txt exists, if not create it
if [ ! -f "$JOURNAL_FILE" ]; then
    touch "$JOURNAL_FILE"
fi

# Get the git diff
DIFF_OUTPUT=$(git diff --staged)

# Check if there are any changes
if [ -z "$DIFF_OUTPUT" ]; then
    echo "No changes detected in git diff."
    exit 0
fi

# Use llm to generate a summary of the changes
LLM_SUMMARY=$(echo "$DIFF_OUTPUT" | llm "Summarize the following git diff changes in a concise and clear way. Output the summary in the following structured format:
- Summary: [One-line summary of the changes]
- Details: [A few bullet points highlighting key changes]

example of expected output:
[2024-01-23] DONE: created template and set the plan to complete basic course by feb 1st week         
[2024-01-24] TODO: start working on the first module of the course
[2024-01-25] updated website 
[2024-01-26] rest
.....
[2024-02-03] wasted time for about a month
[2025-03-11] complete sorting section 
             start cold message for google 
            write intro message and reaso n for absense
")

# Check if the summary is empty
if [ -z "$LLM_SUMMARY" ]; then
    echo "No summary generated by llm."
    exit 1
fi

# Print the summary
echo "Generated summary:"
echo "$LLM_SUMMARY"